"use strict";
const data = {
    americanFootball: [],
    australianRules: [],
    badminton: [],
    baseball: [],
    basketball: [],
    boxing: [],
    cricket: [],
    darts: [],
    esports: [],
    gaelicSports: [],
    golf: [],
    handball: [],
    iceHockey: [],
    motorSport: [],
    netball: [],
    pool: [],
    rugbyLeague: [],
    rugbyUnion: [],
    snooker: [],
    soccer: [],
    tableTennis: [],
    tennis: [],
    ufc: [],
    volleyball: [],
    other: [],
};
